import { D6, MULTIPLIER, PERCENTAGE, RANGE } from "../constants";
import { Trait } from "../types";

export const PERSONALITIES: Trait[] = [
  {
    keyword: "ABSTAINER",
    title: "Abstainer",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.SOME,
        "stats.personality.extroversion": RANGE.BIT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ADAPTABLE",
    title: "Adaptable",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.personality.discipline": RANGE.MORE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ADVENTUROUS",
    title: "Adventurous",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.personality.curiosity": RANGE.MOST,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ADVOCATE",
    title: "Advocate",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.BIT,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "AGITATOR",
    title: "Agitator",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.BIT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ALPHA",
    title: "Alpha",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "AMBITIOUS",
    title: "Ambitious",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MOST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ANTAGONISTIC",
    title: "Antagonistic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.LEAST,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ANXIOUS",
    title: "Anxious",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.SUBTRACT,
        "stats.personality.sensitivity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ARBITER",
    title: "Arbiter",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.intelligence": RANGE.SOME,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ASSERTIVE",
    title: "Assertive",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.extroversion": RANGE.MORE,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "AVOIDANT",
    title: "Avoidant",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "BORING",
    title: "Boring",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.general.stagePresence": D6.ADD,
        "stats.personality.extroversion": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "BUBBLY",
    title: "Bubbly",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.general.leadership": D6.SUBTRACT,
        "stats.personality.sensitivity": RANGE.SOME,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "BULLY",
    title: "Bully",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.gentleness": RANGE.LEAST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CALM",
    title: "Calm",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CHAMPION",
    title: "Champion",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.general.leadership": D6.ADD,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CLUMSY",
    title: "Clumsy",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.BIT,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "COCKY",
    title: "Cocky",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.personality.gentleness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "COMPLAINER",
    title: "Complainer",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CONSERVATIVE",
    title: "Conservative",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.LEAST,
        "stats.personality.happiness": RANGE.BIT,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CONVENTIONAL",
    title: "Conventional",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.SUBTRACT,
        "stats.personality.curiosity": RANGE.LESS,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "COOPERATIVE",
    title: "Cooperative",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "COUNSELOR",
    title: "Counselor",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.personality.intelligence": RANGE.SOME,
        "stats.personality.sensitivity": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CREATIVE",
    title: "Creative",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.personality.curiosity": RANGE.MORE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CURIOUS",
    title: "Curious",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "CYNICAL",
    title: "Cynical",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.LEAST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DECEITFUL",
    title: "Deceitful",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DECEIVER",
    title: "Deceiver",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LEAST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DEFENDER",
    title: "Defender",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DELUSIONAL",
    title: "Delusional",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DILIGENT",
    title: "Diligent",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DIPLOMAT",
    title: "Diplomat",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DISORGANIZED",
    title: "Disorganized",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DISSENTER",
    title: "Dissenter",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DOWN-TO-EARTH",
    title: "Down-to-earth",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DOWNER",
    title: "Downer",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "DUMB",
    title: "Dumb",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.intelligence": RANGE.LEAST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ECCENTRIC",
    title: "Eccentric",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ELOQUENT",
    title: "Eloquent",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.SOME,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ENIGMATIC",
    title: "Enigmatic",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.personality.extroversion": RANGE.BIT,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ENVIOUS",
    title: "Envious",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "EXTRAVAGANT",
    title: "Extravagant",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "EXTROVERTED",
    title: "Extroverted",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MOST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FAIR",
    title: "Fair",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.sincerity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FEARLESS",
    title: "Fearless",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.personality.extroversion": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FEMININE",
    title: "Feminine",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.personality.sensitivity": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FLIRTATIOUS",
    title: "Flirtatious",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MOST,
        "stats.personality.happiness": RANGE.SOME,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FOCUSED",
    title: "Focused",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MORE,
        "stats.personality.happiness": RANGE.BIT,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FOOLISH",
    title: "Foolish",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.BIT,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FORGIVING",
    title: "Forgiving",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FREE_SPIRIT",
    title: "Free Spirit",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LESS,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "FUN-LOVING",
    title: "Fun-loving",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MOST,
        "stats.personality.happiness": RANGE.MOST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "GENTLE",
    title: "Gentle",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "GOOFY",
    title: "Goofy",
    description: "",
    type: "personality",
    group: "faw",
    track: "",
    setup: {
      update: {
        "stats.personality.intelligence": RANGE.BIT,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "GREEDY",
    title: "Greedy",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "GUARDIAN",
    title: "Guardian",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.SUBTRACT,
        "stats.personality.discipline": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HARD-WORKING",
    title: "Hard-working",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MORE,
        "stats.multipliers.luck": MULTIPLIER.ULTRA,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HARDENED",
    title: "Hardened",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.LEAST,
        "stats.personality.happiness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HATER",
    title: "Hater",
    description: "",
    type: "personality",
    group: "mood",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.happiness": RANGE.LEAST,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HERETIC",
    title: "Heretic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HERMIT",
    title: "Hermit",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.BIT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HONEST",
    title: "Honest",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HONORABLE",
    title: "Honorable",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HUMBLE",
    title: "Humble",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "HYPOCRITICAL",
    title: "Hypocritical",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LEAST,
        "stats.personality.intelligence": RANGE.SOME,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "IMPULSIVE",
    title: "Impulsive",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INDIVIDUALIST",
    title: "Individualist",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.extroversion": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INNOCENT",
    title: "Innocent",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INSECURE",
    title: "Insecure",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
        "stats.personality.happiness": RANGE.LESS,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INTELLIGENT",
    title: "Intelligent",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MORE,
        "stats.personality.intelligence": RANGE.MOST,
        "stats.multipliers.luck": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INTENSE",
    title: "Intense",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "INTROVERTED",
    title: "Introverted",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.SUBTRACT,
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.extroversion": RANGE.LEAST,
        "stats.personality.intelligence": RANGE.SOME,
        "stats.skills.memory": PERCENTAGE.UP,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "IRRESPONSIBLE",
    title: "Irresponsible",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "JEALOUS",
    title: "Jealous",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "JOKESTER",
    title: "Jokester",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "JUST",
    title: "Just",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MOST,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "KIND",
    title: "Kind",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "LAZY",
    title: "Lazy",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
        "stats.skills.learning": PERCENTAGE.DOWN,
        "stats.skills.memory": PERCENTAGE.DOWN,
        "stats.skills.stamina": PERCENTAGE.DOWN,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "LONER",
    title: "Loner",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.extroversion": RANGE.LESS,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "LUNATIC",
    title: "Lunatic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.SOME,
        "stats.personality.intelligence": RANGE.BIT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MACHO",
    title: "Macho",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.visual": D6.ADD,
        "stats.personality.gentleness": RANGE.LEAST,
        "stats.personality.intelligence": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MANIAC",
    title: "Maniac",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.personality.intelligence": RANGE.LESS,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MANIPULATIVE",
    title: "Manipulative",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LEAST,
        "stats.personality.intelligence": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MEDIATOR",
    title: "Mediator",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MISCREANT",
    title: "Miscreant",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.LEAST,
        "stats.personality.sincerity": RANGE.LESS,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MISFIT",
    title: "Misfit",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.visual": D6.ADD,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "MODEST",
    title: "Modest",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.sincerity": RANGE.MORE,
        "stats.personality.happiness": RANGE.SOME,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "NARCISSIST",
    title: "Narcissist",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.SUBTRACT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "NARROW-MINDED",
    title: "Narrow-minded",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.LEAST,
        "stats.personality.intelligence": RANGE.BIT,
        "stats.skills.learning": PERCENTAGE.DOWN,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
        "stats.multipliers.style": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "NEUROTIC",
    title: "Neurotic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "NURTURING",
    title: "Nurturing",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.gentleness": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OBNOXIOUS",
    title: "Obnoxious",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.personality.extroversion": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OBSESSIVE",
    title: "Obsessive",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.gentleness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OPENLY_BI",
    title: "Openly bi",
    description: "",
    type: "personality",
    group: "sexuality",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.personality.happiness": RANGE.MOST,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
        "stats.multipliers.style": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OPENLY_GAY",
    title: "Openly gay",
    description: "",
    type: "personality",
    group: "sexuality",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.personality.curiosity": RANGE.SOME,
        "stats.personality.happiness": RANGE.SOME,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OPENLY_TRANS",
    title: "Openly trans",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.SOME,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "OPTIMIST",
    title: "Optimist",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.personality.happiness": RANGE.MOST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ORGANIZED",
    title: "Organized",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.discipline": RANGE.MORE,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PASSIVE",
    title: "Passive",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.SUBTRACT,
        "stats.general.stagePresence": D6.SUBTRACT,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PATIENT",
    title: "Patient",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.sincerity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PERFECTIONIST",
    title: "Perfectionist",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.discipline": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PESSIMIST",
    title: "Pessimist",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.LESS,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PREJUDICED",
    title: "Prejudiced",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.personality.happiness": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PRETENTIOUS",
    title: "Pretentious",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PROMISCUOUS",
    title: "Promiscuous",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.personality.happiness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PROSAIC",
    title: "Prosaic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.general.rhetoric": D6.SUBTRACT,
        "stats.personality.curiosity": RANGE.LEAST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PROTECTOR",
    title: "Protector",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.personality.discipline": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PROUD",
    title: "Proud",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.MORE,
        "stats.personality.gentleness": RANGE.BIT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "PURIST",
    title: "Purist",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RADICAL",
    title: "Radical",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "REBEL",
    title: "Rebel",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RECKLESS",
    title: "Reckless",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.personality.curiosity": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RECLUSE",
    title: "Recluse",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RELAXED",
    title: "Relaxed",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.LEAST,
        "stats.personality.happiness": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RENEGADE",
    title: "Renegade",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.SUBTRACT,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "RESERVED",
    title: "Reserved",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "ROUGH",
    title: "Rough",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SAD",
    title: "Sad",
    description: "",
    type: "personality",
    group: "health",
    track: "",
    setup: {
      update: {
        "stats.personality.happiness": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SECURE",
    title: "Secure",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SELF-CENTERED",
    title: "Self-centered",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.LESS,
        "stats.personality.happiness": RANGE.MOST,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SELFISH",
    title: "Selfish",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.SUBTRACT,
        "stats.personality.sincerity": RANGE.LESS,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SENSITIVE",
    title: "Sensitive",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SENSUAL",
    title: "Sensual",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.stagePresence": D6.ADD,
        "stats.general.charisma": D6.ADD,
        "stats.personality.curiosity": RANGE.MOST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SENTIMENTAL",
    title: "Sentimental",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SHY",
    title: "Shy",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.LEAST,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SKEPTIC",
    title: "Skeptic",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SOCIAL",
    title: "Social",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
        "stats.multipliers.notability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SOCIOPATH",
    title: "Sociopath",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SPIRITUAL",
    title: "Spiritual",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.sincerity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "STUBBORN",
    title: "Stubborn",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "SUBSERVIENT",
    title: "Subservient",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.gentleness": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "TASK-ORIENTED",
    title: "Task-oriented",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.discipline": RANGE.MOST,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "THICK-SKINNED",
    title: "Thick-skinned",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.sensitivity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "TOO_NICE",
    title: "Too nice",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.general.charisma": D6.ADD,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "TRUTH_SEEKER",
    title: "Truth Seeker",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "UNCONVENTIONAL",
    title: "Unconventional",
    description: "",
    type: "personality",
    group: "neutral",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "VAGABOND",
    title: "Vagabond",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {},
    },
    effect: "TDB",
  },
  {
    keyword: "VEGAN",
    title: "Vegan",
    description: "",
    type: "personality",
    group: "identity",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MORE,
        "stats.personality.discipline": RANGE.SOME,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "VILLAIN",
    title: "Villain",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.multipliers.leadership": MULTIPLIER.POSITIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "WARDEN",
    title: "Warden",
    description: "",
    type: "personality",
    group: "quality",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "WITHDRAWN",
    title: "Withdrawn",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.extroversion": RANGE.LEAST,
        "stats.multipliers.notability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "WORKAHOLIC",
    title: "Workaholic",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.general.leadership": D6.ADD,
        "stats.personality.discipline": RANGE.MORE,
        "stats.personality.intelligence": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "WORRYWART",
    title: "Worrywart",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.sensitivity": RANGE.MOST,
        "stats.multipliers.likeability": MULTIPLIER.NEGATIVE,
      },
    },
    effect: "TDB",
  },
  {
    keyword: "BLABBER",
    title: "Blabber",
    description: "",
    type: "personality",
    group: "flaw",
    track: "",
    setup: {
      update: {
        "stats.personality.curiosity": RANGE.MORE,
        "stats.personality.sincerity": RANGE.SOME,
      },
    },
    effect: "TDB",
  },
];
